### ISSUE TITLE
XLIFF 2.1 - Example in 4.3.1.40 type is invalid

### ISSUE THREAD

**Issue by yumaoka** [oasis-tcs/xliff-xliff-22#10]
```
<segment>
  <source xml:lang="cs"><pc type="quote">Blázen,
      chce dobýt točnu v takovém počasí</pc>, dodal slovy svého
      oblíbeného imaginárního autora.</source>
  <target xml:lang="en"><pc type="quote">Madman, he wants to conquer the
      pole in this weather</pc>, offered he the words of his
      favourite imaginary playwright.</target>
</segment>
```

The example above illustrates the use of `type="quote"` with `<pc>` element. The `id` attribute is required in each `<pc>` element, but the example is missing the attribute.

In addition to this, I personally don't like to put `xml:lang` attribute in this example. I think the original author's intent was to clarify what is source/target language in this example. But even without it, it should be sufficient to illustrate the use of `type="quote"` with `<pc>` element.

**Comment by rmraya** [comment]
Fixed in current draft

**Comment by DavidFatDavidF** [comment]
Check if the xml:lang was kept
