### ISSUE TITLE
Remove requirement to register prefix

### ISSUE THREAD

**Issue by rmraya** [oasis-tcs/xliff-xliff-22#12]
Original issue: [https://github.com/rmraya/OpenXLIFF/issues/13](https://github.com/rmraya/OpenXLIFF/issues/13) 

Remove the requirement to register prefixes for subState attribute in next version of XLIFF

**Comment by DavidFatDavidF** [comment]
The XLIFF spec doesn't contain a requirement to register subState prefixes (it contains a permission to register them)
See my response in https://github.com/rmraya/OpenXLIFF/issues/13
In summary correct validation behavior can be implemented w/o changing the XLIFF specification

**Comment by DavidFatDavidF** [comment]
As discussed today, this issue should be closed w/o changing the spec.
