### ISSUE TITLE
[Core Proposal] Add examples to explain processing requirements of state attribute

### ISSUE THREAD

**Issue by yumaoka** [oasis-tcs/xliff-xliff-22#14]
### Authors

Yoshito Umaoka

### Area of Changes

- [X] XLIFF specification document
- [ ] XLIFF schema
- [ ] XLIFF validator
- [X] Example files

### Detailed Description

XLIFF 2.1 specification section [4.3.1.31 state](http://docs.oasis-open.org/xliff/xliff-core/v2.1/os/xliff-core-v2.1-os.html#state), defines the default value is "initial". In the processing requirements section, the following description is found.

---

Writers MUST NOT set the state attribute values to other than the default initial if and only if the segment  element where the attribute is set doesn't have the<target> child.

---

This description is hard to understand for implementors because "only if" with double negative. It is not really clear if following example is valid.

```
<xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0"
    srcLang="en" trgLang="fr">
  <file id="f1">
    <unit id="u1">
      <segment id="s1" state="initial">
        <source>Hello World!</source>
        <target>Bonjour le Monde!</target>
      </segment>
    </unit>
  </file>
</xliff>
```

### Compatibility Impacts

N/A

**Comment by rmraya** [comment]
Processing requirements for `state` have been clarified in the specification

**Comment by yumaoka** [comment]
b5612b464a013bd7c776d8db408394166eab6569 updated the description. I agree new text is much easier to understand.
