### ISSUE TITLE
[Core Proposal] Refine constraint for <sc> and <ec>

### ISSUE THREAD

**Issue by yumaoka** [oasis-tcs/xliff-xliff-22#15]
### Authors

Yoshito Umaoka

### Area of Changes

- [X] XLIFF specification document
- [ ] XLIFF schema
- [ ] XLIFF validator
- [ ] Example files

### Detailed Description

In XLIFF 2.1 [specification 4.2.3.4 sc](http://docs.oasis-open.org/xliff/xliff-core/v2.1/os/xliff-core-v2.1-os.html#sc), there is a constraint statement below:

---

The attribute [isolated](http://docs.oasis-open.org/xliff/xliff-core/v2.1/os/xliff-core-v2.1-os.html#isolated) MUST be set to yes if and only if the [<ec>](http://docs.oasis-open.org/xliff/xliff-core/v2.1/os/xliff-core-v2.1-os.html#ec) element corresponding to this start marker is not in the same [<unit>](http://docs.oasis-open.org/xliff/xliff-core/v2.1/os/xliff-core-v2.1-os.html#unit), and set to no otherwise.

---

This constraint makes perfect sense for `<source>` part . However, in translation process, not all `<target>` values might not be ready at a point.

```
<unit id="1">
  <segment id="seg1" state="translated">
    <source><sc id="1" type="fmt" subType="xlf:b"/>
        First sentence. </source>
    <target><sc id="1" type="fmt" subtype="xlf:b"/>
        最初の文。</target>
  </segment>
  <segment id="seg2">
    <source>Second sentence.<ec startRef="1" type="fmt"
        subType="xlf:b"/></source>
  </segment>
</unit>
```

The example above is invalid with the current XLIFF specification because `<sc id="1" ...>` in `seg1` is not `isolated="yes"` although it does not have the corresponding `<ec>` element in `seg2`. The specification should be updated to clarify the constraint:

- This constraint always applies to `<source>` values in a `<unit>`.
- For <target> values, this constraint is effective when all `<segment>`s in a `<unit>`  have `<target>` elements.
- 

### Example Use Case

N/A

### Compatibility Impacts

This specification update should have very small or no impacts to existing XLIFF applications.

**Comment by rmraya** [comment]
Processing requirements for `<sc>` have been adjusted in the specification

**Comment by yumaoka** [comment]
Description updated by 6b0037e17649e0bef98ef6446c4dfd7ea0cc35fb clarified the constraint.
