### ISSUE TITLE
[Erratum] Normative keywords should follow BCP 14

### ISSUE THREAD

**Issue by DavidFatDavidF** [oasis-tcs/xliff-xliff-22#16]
### Detailed Description

Currently the spec references RFC 2119 which is only the first part of BCP 14. Since May 2017, BCP 14 also contains RFC 8174, which is very important for interpretation of normative keywords.
The keywords section should be changed to reference BCP 14 and also the normative reference should be changed from RFC 2119 to BCP 14.

**Comment by rmraya** [comment]
Updated references and capitalized keywords to comply with RFC 8174
