### ISSUE TITLE
[Erratum] The example in "5.8.8.2.2 Inline Elements" should extract the `alt`

### ISSUE THREAD

**Issue by mihnita** [oasis-tcs/xliff-xliff-22#22]
### Specification Type

None

### Detailed Description

This issue can happens in the "5.8.8.2.2 Inline Elements" section in `xliff-extended-v2.2wd.html`

The html content being extracted is
```html
    <p>Image: <img src="example.png" alt="Text for the image"></p>
```
and it is extracted as:
```xml
<unit id="1">
  <res:resourceData>
    <res:resourceItem id="r1" mimeType="image/png" context="no">
      <res:source href="example.png" />
    </res:resourceItem>
  </res:resourceData>
  <segment>
    <source>Image: <ph id="ph1" fs="img"
        subFs="src,example.png\alt,Text for the image" /></source>
  </segment>
</unit>
```

But the `alt` element is localisable, and _"Text for the image"_ should be extracted in a subflow `<unit>`, as described in the "4.7.4 Sub-Flows"  section.

**Comment by rmraya** [comment]
Fixed in Mihai's PR
