### ISSUE TITLE
migrate ISO format code repo

### ISSUE THREAD

**Issue by DavidFatDavidF** [oasis-tcs/xliff-xliff-22#3]
We need to migrate the ISO templated XLIFF Version 2.2 repo from OASIS SVN

**Comment by DavidFatDavidF** [comment]
ISO 21720:2017 will be under periodic review this year (2022) in ISO/TC 37/SC 5
https://www.iso.org/standard/71490.html
Creating an ISO formatted version of XLIFF Version 2.1 would be needed if we intend to maintain the ISO published version

**Comment by rmraya** [comment]
XLIFF 2.1 was officially submitted to ISO for fast-track approval by Jamie Clark on October 31, 2023.
