### ISSUE TITLE
Clarify validation of core elements in modules

### ISSUE THREAD

**Issue by rmraya** [oasis-tcs/xliff-xliff-22#9]
Add a section indicating that validation rules for core elements don't apply in full when the element is used inside a module.

Example: "id" attribute for &lt;data> element must be unique inside &lt;unit>, but when &lt;originalData> is used in &lt;unit> and also in &lt;mtc:match>, duplication of "id" may be necessary.

**Comment by DavidFatDavidF** [comment]
Will provide explanatory prose

**Comment by DavidFatDavidF** [comment]
No action required.
The explanatory note already exists in the published XLIFF 2.1 standard
http://docs.oasis-open.org/xliff/xliff-core/v2.1/os/xliff-core-v2.1-os.html#id

> Note
> All of the above defined uniqueness scopes ignore Module and Extension data. It would be impossible to impose those uniqueness requirements onto Module or Extension data. As Core only Modifiers could inadvertently cause conflicts with Modules or Extensions based data they cannot access. Modules and Extensions reusing Core need to specify their own uniqueness scopes for the [xlf:id](http://docs.oasis-open.org/xliff/xliff-core/v2.1/os/xliff-core-v2.1-os.html#id). In general, Modules and Extensions are advised to mimic the Core uniqueness requirement within their specific wrapper elements enclosing the reused Core elements or attributes, yet Module or Extensions are free to set wider uniqueness scopes if it makes business sense.

**Comment by DavidFatDavidF** [comment]
Also based on discussion in meeting on 16th August
This is addressed in the Translation Candidates Module
http://docs.oasis-open.org/xliff/xliff-core/v2.1/os/xliff-core-v2.1-os.html#candidates
